### ISSUE TITLE
Error spam console

### ISSUE THREAD

**Issue by WareZ57** [JimiIT92/UniverseGuard2#55]
Hello, recently i using your plugin but sometime is spam console with error & kick all player in game.

[23:15:53] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.17, description=An easy to use world protection plugin for Sponge, authors=[JimiIT92, Brycey92, eheimer], source=./mods/UniverseGuard-2.17.jar}
java.lang.NullPointerException: null
[23:15:53] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.17, description=An easy to use world protection plugin for Sponge, authors=[JimiIT92, Brycey92, eheimer], source=./mods/UniverseGuard-2.17.jar}
java.lang.NullPointerException: null
at com.universeguard.event.flags.FlagFarewellListener.handleEvent(FlagFarewellListener.java:47) ~[FlagFarewellListener.class:?]
at com.universeguard.event.flags.FlagFarewellListener.onFarewell(FlagFarewellListener.java:33) ~[FlagFarewellListener.class:?]
at org.spongepowered.common.event.listener.MoveEntityEventListener_FlagFarewellListener_onFarewell129.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3481]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:458) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3481]
at net.minecraft.network.NetHandlerPlayServer.redirect$throwMoveEvent$zio000(NetHandlerPlayServer.java:2315) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:462) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) [lk.class:?]
at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) [lk$a.class:?]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2705-7.1.0-BETA-3481]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3481]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

UniverseGuard Lasted version
spongeforge-1.12.2-2705-7.1.0-BETA-3481
Forge 14.23.5.27

Thanks you !

**Comment by JimiIT92** [comment]
Did you have any custom dimension in your server? If so the problem could be that the dimension global region file hasn't been generated (See [the release sponge post](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/187) to know why). Latest version of UniverseGuard adds a command to force the generation of this file so those kind of errors should be gone. If this is the case then try running [this command](https://github.com/JimiIT92/UniverseGuard2/wiki/rg-globalfor) and see if that works ;)

**Comment by WareZ57** [comment]
Thanks you worked fine ! ;)
