### ISSUE TITLE
Can't teleport to the newly created spawn location for some reason.

### ISSUE THREAD

**Issue by DeaSTL** [JimiIT92/UniverseGuard2#60]
using spongeforge-1.12.2-2768-7.1.4
and UniverseGuard-2.17

`
[22:19:06] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg create 34852 1 88855 34248 254 89532 Spawn
[22:20:15] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg create 34852 1 88855 34248 254 89532 overworld overworld Spawn
[22:21:41] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg create 34852 1 88855 34248 254 89532 minecraft:overworld world Spawn
[22:21:50] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg info Spawn
[22:22:56] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg setspawn 34575 179 89205
[22:23:07] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg spawn Spawn
[22:23:07] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'rg spawn Spawn' for source EntityPlayerMP['DeaSTL'/616, l='world', x=34575.45, y=180.00, z=89205.72]: The location was null!
java.lang.NullPointerException: The location was null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraft.entity.Entity.setLocation(Entity.java:5325) ~[vg.class:?]
        at com.universeguard.command.RegionSpawnExecutor.execute(RegionSpawnExecutor.java:44) ~[RegionSpawnExecutor.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.4]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.4]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.4]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.4]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.4]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.4]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[22:26:31] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg save
[22:26:38] [Server thread/INFO] [nucleus]: DeaSTL ran the command: /rg spawn Spawn
[22:26:38] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'rg spawn Spawn' for source EntityPlayerMP['DeaSTL'/616, l='world', x=34571.49, y=200.02, z=89210.54]: The location was null!
java.lang.NullPointerException: The location was null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraft.entity.Entity.setLocation(Entity.java:5325) ~[vg.class:?]
        at com.universeguard.command.RegionSpawnExecutor.execute(RegionSpawnExecutor.java:44) ~[RegionSpawnExecutor.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.4]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.4]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.4]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.4]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.4]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.4]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
`

It doesn't seem to let me teleport to the spawn.

**Comment by DeaSTL** [comment]
I solved my issue, I think I just had a old config. Also I fixed the rg create command in my fork of Universe Guard 2
